name: Publish to Maven

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  SLNE_SNAPSHOTS_REPO_USERNAME: ${{ secrets.MAVEN_SNAPSHOTS_USERNAME }}
  SLNE_SNAPSHOTS_REPO_PASSWORD: ${{ secrets.MAVEN_SNAPSHOTS_PASSWORD }}
  SLNE_RELEASES_REPO_USERNAME: ${{ secrets.MAVEN_RELEASES_USERNAME }}
  SLNE_RELEASES_REPO_PASSWORD: ${{ secrets.MAVEN_RELEASES_PASSWORD }}
  MODULE_REGEX: "surf-gui-api.*-all\\.jar$|surf-gui-bukkit.*-all\\.jar$|surf-gui-velocity.*-all\\.jar$"

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: '21'

      - name: Build Project
        run: ./gradlew clean build

      - name: Publish to Maven Snapshots
        run: ./gradlew publish

      - name: Extract Project Version
        id: get_version
        run: echo "VERSION=$(./gradlew properties | grep "^version:" | awk '{print $2}')" >> $GITHUB_ENV

      - name: Find and filter JAR files
        id: find_jars
        run: |
          echo "JAR_FILES<<EOF" >> $GITHUB_ENV
          find . -path "**/build/libs/*.jar" | grep -E "${{ env.MODULE_REGEX }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            ${{ env.JAR_FILES }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}