name: Publish to Maven

on:
  push:
    branches:
      - master

env:
  MAVEN_SNAPSHOTS_USERNAME: ${{ secrets.MAVEN_SNAPSHOTS_PASSWORD }}
  MAVEN_SNAPSHOTS_PASSWORD: ${{ secrets.MAVEN_SNAPSHOTS_PASSWORD }}
  MAVEN_RELEASES_USERNAME: ${{ secrets.MAVEN_RELEASES_USERNAME }}
  MAVEN_RELEASES_PASSWORD: ${{ secrets.MAVEN_RELEASES_PASSWORD }}

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: '21'
      - name: Build with Gradle
        run: ./gradlew shadowJar
      - name: Publish to Maven
        run: ./gradlew publish